language: node_js

node_js:
  - "node"

sudo: required
dist: trusty

branches:
  except:
    - release

before_script:
    - sudo npm install -g jake jake-utils
    - sudo npm install fs colors

script:
  - jake build
  - jake test
