language: node_js

node_js:
  - "node"

sudo: required
dist: trusty

group: edge

branches:
  except:
    - release

before_script:
    - npm install chai
    - npm install -g mocha
    - npm install -g coveralls
    - npm install -g istambul
    - npm install -g nyc

script:
  - npm run coverage

after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls