language: node_js

node_js:
  - "node"

sudo: required
dist: trusty

branches:
  except:
    - release

before_script:
    - npm install -g jake
    - npm install -g jake-utils
    - npm install fs
    - npm install colors

script:
  - jake build
  - jake test
